/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ZlibDecompressor {
  constructor(chunkSize: number)
  push(data: Buffer): { ok: true; data?: Buffer; } | { ok: false; error: string }
}
